config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  resources :forms, :fields, :responses

  resources :forms do
    resources :logs, only: [ :new, :edit, :create, :update ]
  end

  resources :logs, expect: [ :new, :edit, :create, :update ]
end

app/models/form.rb
# == Schema Information
#
# Table name: forms
#
#  id           :bigint           not null, primary key
#  active       :boolean          default(FALSE), not null
#  discarded_at :datetime
#  name         :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_forms_on_discarded_at     (discarded_at)
#  index_forms_on_name_and_active  (name,active) UNIQUE
#

class Form < ApplicationRecord
  include Discard::Model

  validates :name, presence: true
  validates :name, uniqueness: { scope: :active }

  has_and_belongs_to_many :fields
  has_many :logs

  scope :active, -> { kept.where(active: true) }
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_form, only: %i[ show edit update destroy ]

  def index
    @forms = Form.kept
  end

  def show
  end

  def new
    @form = Form.new
  end

  def create
    @form = Form.new(form_params)
    if @form.save
      redirect_to @form, notice: "Form Created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @form.update(form_params)
      redirect_to @form, notice: "Form Updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @form.discard
    redirect_to forms_path, notice: "Form Deleted!"
  end

  private

  def set_form
    @form = Form.kept.find_by(id: params[:id])
    @fields = @form.fields.kept.order(:created_at)
    redirect_to root_path,  warning: "can't find form with that id" if @form.nil?
  end

  def form_params
    params.expect(form: [ :name, :active, field_ids: [] ])
  end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_with model: form do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name, required: true  %>

    <%= form.label :active %>
    <%= form.check_box :active  %>

    <h3>Fields</h3>
    <%= form.collection_checkboxes :field_ids, Field.kept.order(:created_at), :id, :short_prompt, multiple: true %>
    
    <%= form.submit %>
<% end %>

app/views/forms/edit.html.erb
<h1>Edit <%= Form.model_name.human %></h1>

<%= link_to "Cancel", @form %>

<%= render "form", form: @form %>

app/views/forms/index.html.erb
<h1><%= Form.model_name.human.pluralize %></h1>

<%= link_to "New #{Form.model_name.human}", new_form_path %>

<ul>
    <% @forms.each do |form| %>
        <li><%= link_to form.name, form %></li>
    <% end %>
</ul>

app/views/forms/new.html.erb
<h1>New <%= Form.model_name.human %></h1>

<%= link_to "Cancel", forms_path %>

<%= render "form", form: @form %>

app/views/forms/show.html.erb
<h1><%= @form.name %></h1>

<%= link_to "Back", forms_path %>
<%= link_to "Edit", edit_form_path(@form) %>
<%= link_to "Delete", form_path(@form), data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>

<p><%= @form.active ? "Active" : "Inactive" %></p>

<h3>Fields</h3>
<ul>
    <% @fields.each do |field| %>
        <li><%= link_to field.prompt, field %></li>
    <% end %>
</ul>