config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  resources :forms, :fields, :responses

  resources :forms do
    resources :logs, only: [ :new, :edit, :create, :update ]
  end

  resources :logs, expect: [ :new, :edit, :create, :update ]
end

app/models/log.rb
# == Schema Information
#
# Table name: logs
#
#  id         :bigint           not null, primary key
#  date       :date             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  form_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_logs_on_form_id  (form_id)
#  index_logs_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (form_id => forms.id)
#  fk_rails_...  (user_id => users.id)
#
#  fk_rails_...  (form_id => forms.id)
#  fk_rails_...  (user_id => users.id)


class Log < ApplicationRecord
  validates :date, presence: true

  belongs_to :user
  belongs_to :form
  has_many :responses, dependent: :destroy
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_log, only: %i[ show edit update destroy ]
  before_action :set_form, only: %i[ new create edit update ]

  def index
    @logs = Log.where(user: current_user).order(date: :desc)
  end

  def show
  end

  def new
    @log = Log.new
  end

  def create
    @log = Log.new(log_params.first)
    @log.form = @form
    @log.user = current_user
    if @log.save
      create_responses(log_params.last)
      redirect_to @log, notice: "Log Created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @log.update(log_params.first)
      update_responses(log_params.last)
      redirect_to @log, notice: "Log Updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @log.destroy
    redirect_to logs_path, notice: "Log Deleted"
  end

  private

  def set_log
    @log = Log.find_by(id: params[:id], user: current_user)
    redirect_to root_path,  warning: "can't find log with that id" if @log.nil?
  end

  def set_form
    @form = Form.find_by(id: params[:form_id])
    redirect_to root_path,  warning: "can't find form with that id" if @form.nil?
  end

  def log_params
    params.expect(log: [ :date ], field: @form.fields.pluck(:key).map { |f| f.to_sym })
  end

  def create_responses(field_params)
    @form.fields.each do |field|
      response = Response.new
      response.text = field_params[field.key]
      response.log = @log
      response.field = field
      response.save
    end
  end

  def update_responses(field_params)
    @log.responses.each do |r|
      r.update(text: field_params[r.field.key])
    end
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_with model: [form, log] do |f| %>
    <%= f.label :date %>
    <%= f.date_field :date, value: Date.today %>

    <% form.fields.order(:created_at).each do |field| %>
        <%= label :field, field.key, field.prompt %>
        <%= textarea :field, field.key, placeholder: field.help_text, required: true, value: field.responses.find_by(log_id: @log.id)&.text %>
    <% end %>
    
    <%= f.submit %>
<% end %>

app/views/logs/edit.html.erb
<h1>Edit <%= @form.name %></h1>

<%= link_to "Cancel", logs_path %>

<%= render "form", log: @log, form: @form %>

app/views/logs/index.html.erb
<h1><%= Log.model_name.human.pluralize %></h1>

<ul>
    <% @logs.each do |log| %>
        <li><%= link_to log.date, log %></li>
    <% end %>
</ul>

app/views/logs/new.html.erb
<h1>New <%= @form.name %></h1>

<%= link_to "Cancel", logs_path %>

<%= render "form", log: @log, form: @form %>

app/views/logs/show.html.erb
<h1><%= @log.date %></h1>

<%= link_to "Back", logs_path %>
<%= link_to "Edit", edit_form_log_path(@log.form, @log) %>
<%= link_to "Delete", log_path(@log), data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>

<table>
  <thead>
    <tr>
      <th scope="col">Field</th>
      <th scope="col">Response</th>
    </tr>
  </thead>
  <tbody>
    <% @log.responses.each do |r| %>
      <tr>
        <th scope="row"><%= r.field.short_prompt %></th>
        <td><%= r.text %></td>
      </tr>    
    <% end %>
  </tbody>
</table>