config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  resources :forms, :fields, :responses

  resources :forms do
    resources :logs, only: [ :new, :edit, :create, :update ]
  end

  resources :logs, expect: [ :new, :edit, :create, :update ]
end

app/models/field.rb
# == Schema Information
#
# Table name: fields
#
#  id           :bigint           not null, primary key
#  discarded_at :datetime
#  help_text    :string
#  key          :string           not null
#  prompt       :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_fields_on_discarded_at  (discarded_at)
#  index_fields_on_key           (key) UNIQUE
#

class Field < ApplicationRecord
  include Discard::Model

  validates :prompt, presence: true
  validates :key, presence: true, uniqueness: true

  has_and_belongs_to_many :forms
  has_many :responses

  def short_prompt
    prompt.truncate(30)
  end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_field, only: %i[ show edit update destroy ]

  def index
    @fields = Field.kept.order(:created_at)
  end

  def show
  end

  def new
    @field = Field.new
  end

  def create
    @field = Field.new(field_params)
    @field.key = @field.prompt.partition(" ").first.downcase.gsub(/[^0-9A-Za-z]/, "").to_sym
    if @field.save
      redirect_to @field, notice: "Field Created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @field.update(field_params)
      redirect_to @field, notice: "Field Updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @field.discard
    redirect_to fields_path, notice: "Field Deleted!"
  end

  private

  def set_field
    @field = Field.kept.find_by(id: params[:id])
    redirect_to fields_path,  warning: "can't find field with that id" if @field.nil?
  end

  def field_params
    params.expect(field: [ :prompt, :help_text, form_ids: [] ])
  end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_form.html.erb
<%= form_with model: field do |form| %>
    <%= form.label :prompt %>
    <%= form.text_field :prompt, required: true %>

    <%= form.label :help_text %>
    <%= form.text_field :help_text %>

    <h3>Forms</h3>
    <%= form.collection_checkboxes :form_ids, Form.kept.order(:name), :id, :name, multiple: true %>
    
    <%= form.submit %>
<% end %>

app/views/fields/edit.html.erb
<h1>Edit <%= Field.model_name.human %></h1>

<%= link_to "Cancel", @field %>

<%= render "form", field: @field %>

app/views/fields/index.html.erb
<h1><%= Field.model_name.human.pluralize %></h1>

<%= link_to "New #{Field.model_name.human}", new_field_path %>

<ul>
    <% @fields.each do |field| %>
        <li><%= link_to field.short_prompt, field %></li>
    <% end %>
</ul>

app/views/fields/new.html.erb
<h1>New <%= Field.model_name.human %></h1>

<%= link_to "Cancel", fields_path %>

<%= render "form", field: @field %>

app/views/fields/show.html.erb
<h1><%= @field.id %></h1>

<%= link_to "Back", fields_path %>
<%= link_to "Edit", edit_field_path(@field) %>
<%= link_to "Delete", field_path(@field), data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>

<table>
  <thead>
    <tr>
      <th scope="col">Prompt</th>
      <th scope="col">Help text</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= @field.prompt %></th>
      <td><%= @field.help_text %></td>
    </tr>     
</table>

<h3>Forms</h3>
<ul>
    <% @field.forms.kept.each do |form| %>
        <li><%= link_to form.name, form %></li>
    <% end %>
</ul>