config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  resources :forms, :fields, :responses

  resources :forms do
    resources :logs, only: [ :new, :edit, :create, :update ]
  end

  resources :logs, expect: [ :new, :edit, :create, :update ]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "The Mind Electric" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <%= favicon_link_tag asset_path('favicon.png') %>
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <header>

        <nav>
          <ul>
            <li>
              <hgroup>
                <h1>The Mind Electric</h1>
                <p>See how the brain plays around</p>
              </hgroup>
            </li>
          </ul>          
          <ul>
            <li><%= link_to "Home", user_signed_in? ? logs_path : root_path %></li>
            <% if user_signed_in? %>
              <li>
                <details class="dropdown">
                <summary>
                  New
                </summary>
                <ul dir="rtl">
                  <% Form.active.each do |f| %>
                    <li><%= link_to f.name, new_form_log_path(f) %></li>
                  <% end %>
                </ul>
              </details>
              </li>              

              <li>
                <details class="dropdown">
                <summary>
                  Admin
                </summary>
                <ul dir="rtl">
                  <li><%= link_to Form.model_name.human.pluralize, forms_path %></li>
                  <li><%= link_to Field.model_name.human.pluralize, fields_path %></li>
                </ul>
              </details>
              </li>
              <li><%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete } %></li>
            <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
          </ul>
        </nav>
      </header>  
      <main>
        <% flash.each do |type, msg| %>
          <div id="flash-wrapper">
            <div class="flash-container">
              <div class="flash <%= type %>"><%= msg %>
              </div>
            </div>
          </div>
        <% end %>
        <%= yield %>
      </main>
      <footer>
        <small></small>
      </footer>
  </body>
</html>